### ISSUE TITLE
VAWGAN model support

### ISSUE THREAD

**Issue by triwoods** [JeremyCCHsu/vc-vawgan#2]
Hi Jeremy,

I found there are trainer code regarding the VAWGAN and the option for choosing VAWGAN in the main.py script, but in the model directory, there is no VAWGAN code, would it be possible to add the VAWGAN code in the model?

**Comment by JeremyCCHsu** [comment]
Please refer to the `vawgan` branch in the [code base](https://github.com/JeremyCCHsu/vae-npvc).
